services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - .:/app
      - go-cache:/go 
    environment:
      - CGO_ENABLED=0
    tty: true 
    stdin_open: true

volumes:
  go-cache:
